$('#card').click(function() {
  $('.card').css('display', 'block');
  $('.basic').css('display', 'none');
  $('.det').css('display', 'none');
  $('.cus').css('display', 'none');
  $('.footer').css('display', 'block');
  $('.save').html("保存");
  $('#card').addClass('on');
  $('#cus').removeClass('on');
  $('#basic').removeClass('on');
  $('#det').removeClass('on');
  $('#tab-b').addClass('tab-bottom');
  $('#tab-a').removeClass('tab-bottom');
  $('#tab-c').removeClass('tab-bottom');
  $('#tab-d').removeClass('tab-bottom');
});
$('#det').click(function() {
  $('.det').css('display', 'block');
  $('.basic').css('display', 'none');
  $('.card').css('display', 'none');
  $('.cus').css('display', 'none');
  $('.footer').css('display', 'none');
  $('#det').addClass('on');
  $('#cus').removeClass('on');
  $('#basic').removeClass('on');
  $('#card').removeClass('on');
  $('#tab-c').addClass('tab-bottom');
  $('#tab-a').removeClass('tab-bottom');
  $('#tab-b').removeClass('tab-bottom');
  $('#tab-d').removeClass('tab-bottom');
});
$('#cus').click(function() {
  $('.cus').css('display', 'block');
  $('.basic').css('display', 'none');
  $('.det').css('display', 'none');
  $('.card').css('display', 'none');
  $('.footer').css('display', 'none');
  $('#cus').addClass('on');
  $('#card').removeClass('on');
  $('#basic').removeClass('on');
  $('#det').removeClass('on');
  $('#tab-d').addClass('tab-bottom');
  $('#tab-a').removeClass('tab-bottom');
  $('#tab-b').removeClass('tab-bottom');
  $('#tab-c').removeClass('tab-bottom');
});
$('#basic').click(function() {
  $('.basic').css('display', 'block');
  $('.cus').css('display', 'none');
  $('.det').css('display', 'none');
  $('.card').css('display', 'none');
  $('.footer').css('display', 'none');
  // $('.save').html("保存");
  $('#basic').addClass('on');
  $('#card').removeClass('on');
  $('#cus').removeClass('on');
  $('#det').removeClass('on');
  $('#tab-a').addClass('tab-bottom');
  $('#tab-b').removeClass('tab-bottom');
  $('#tab-c').removeClass('tab-bottom');
  $('#tab-d').removeClass('tab-bottom');
});
